### ISSUE TITLE
The Wheel and the svgs aren't responsive

### ISSUE THREAD

**Issue by soumita21** [codescale/Wheel-Of-Life#1]
That's an amazing representation with all the svg and javascript, but is there a way to make it responsive? I tried a lot to do so but every time the background of the container and the svgs won't coincide. Can you help with this?

**Comment by codescale** [comment]
Hi. I'm glad you like this little tool :) I tried to get the graph on top more responsive here #2 Are you able to check it out? Cheers Matt

**Comment by soumita21** [comment]
Thank you so much. It was really helpful. 
Also, I tried on an iPhone but turns out that the onchange function wasn't working on changing the slider. I searched for it on the net and I found that you could use onblur maybe. Let me know your views on this.
And thank you so much again. Really saved my day.
Regards 
Soumita

**Comment by codescale** [comment]
Hi. Can you open another ticket for the slider issue? Thx
