### ISSUE TITLE
Example Wheel of Life PNG is not the same as the generated (download) PNG

### ISSUE THREAD

**Issue by armaccloud** [codescale/Wheel-Of-Life#10]
When I look in the document structure of the app, there is an example Wheel of Life PNG in the doc folder, which has numbering and edge colors included. It looks like this.

![image](https://user-images.githubusercontent.com/9272078/122653642-327e8380-d146-11eb-81ab-8d993290e891.png)

The generated PDF from the download function misses the numbering and edge colors. It looks like this.

![image](https://user-images.githubusercontent.com/9272078/122653679-77a2b580-d146-11eb-84c8-153e5a0d5c83.png)

Is it an idea to use the 1st (example) PNG instead?

**Comment by codescale** [comment]
You‘re right. The export/download feature required to develop the whole wheel as svg (was a png before). And it simply means additional effort to have the colors at the outer ring and the numbers. Let‘s keep this as an additional feature :)
