### ISSUE TITLE
Longer categories not displayed correct in the edges on Firefox

### ISSUE THREAD

**Issue by armaccloud** [codescale/Wheel-Of-Life#11]
Within Chromium / Brave, the edges of the Wheel of Life display the text well (I believe 2 of them have a smaller text size defined in the code). 

![image](https://user-images.githubusercontent.com/9272078/122653763-32cb4e80-d147-11eb-978f-88b636d08829.png)

When I open the same wheel in Firefox, it does not display well.

![image](https://user-images.githubusercontent.com/9272078/122653787-5db5a280-d147-11eb-9f2c-21972b9732c1.png)

This is occurring on Firefox 89.0.1 (64-bit)

**Comment by codescale** [comment]
I added a PR #13 which may fix this issue. Are you able to test it?

**Comment by armaccloud** [comment]
It works for me, cheers!
