### ISSUE TITLE
Titles of Wheel of Life are overlapping each other

### ISSUE THREAD

**Issue by donaral** [codescale/Wheel-Of-Life#15]
Hi there, 
go to https://codescale.github.io/Wheel-Of-Life/ 
the titles of each section is on top of each other 

 
<img width="1149" alt="WheelOfLife-text-bug" src="https://user-images.githubusercontent.com/11408945/143915244-7c2d8fc0-3594-4c36-973d-1b7d377c38c6.png">

**Comment by codescale** [comment]
Hi @donaral can you tell me a bit more about the browser you're using ... which one and which version. Because it works in quite a few, but seems to be wrong for the one you use :)
Thx

**Comment by codescale** [comment]
If you still have this problem feel free to reopen the issue.
