### ISSUE TITLE
Wheel Of Life Extended

### ISSUE THREAD

**Issue by TerryBowler01** [codescale/Wheel-Of-Life#16]
Hi, i have been playing around with this code and would like (if possible) a larger version (so the titles do not overlap) with 12 sections as opposed to the one with 8, i have tried to play around with the code and add extra sections but they appear to overlap and i cannot quite figure it out, any help would be appreciated to create a larger 12 section wheel that works the same, just with four extra sections, thank you in advance.

**Comment by codescale** [comment]
Now it's possible to easily adjust the index.html and change the config...
