### ISSUE TITLE
Slider doesn't work for all devices. 

### ISSUE THREAD

**Issue by soumita21** [codescale/Wheel-Of-Life#3]
I tried the slider on an iPhone and on android too apart from my laptop. Looks like the onchange function that calls the adjustScale  doesn't get fired on ios somehow. I added an onblur event on the same line, works somehow. Do you think its correct? If not how can it be solved?

**Comment by codescale** [comment]
Weird as it works for me on ios 13 and safari. Do you use another browser?

**Comment by soumita21** [comment]
Well, as a matter of fact it works for me and I use android. It's my friend who faced this issue.

**Comment by codescale** [comment]
I hope my solution fixed the issue. Otherwise feel free to reopen.
