### ISSUE TITLE
How can we make headers of wheel editable

### ISSUE THREAD

**Issue by mominnawaf** [codescale/Wheel-Of-Life#6]
How can we make headers of wheel editable?
Also SVG would be better option!

**Comment by codescale** [comment]
Hi mominnawaf,

with headers you mean those titles like `Finance`, `Health`, ...? I wonder why you need them editable? I can imagine if you wanna change them you also have to change the description. Is that what you have in mind?

Regarding the SVG. Actually a part of the "wheel" is already SVG. But just lately I started an experiment to develop the whole wheel in SVG. May I ask why you would like to see it in SVG?

Cheers, Matt

**Comment by mominnawaf** [comment]
With headers I mean those titles like `Finance`, `Health `etc. Because I want custom headers

**Comment by codescale** [comment]
Great. And if you wanna add custom headers you also want to add a custom description for each of them?

**Comment by mominnawaf** [comment]
That would be awesome!!

**Comment by codescale** [comment]
Now it's possible to adjust the index.html and change the name and/or description of every section...
