### ISSUE TITLE
Download results in an empty PNG

### ISSUE THREAD

**Issue by armaccloud** [codescale/Wheel-Of-Life#9]
When I download the PNG, this does not contain the generated wheel of life.
![image](https://user-images.githubusercontent.com/9272078/122521278-eda6ff80-d014-11eb-8cff-ef8ecc422490.png)
**Steps to reproduce**
1. Go to https://codescale.github.io/Wheel-Of-Life/
2. Click on the download button
3. Verify the wheel of life of not generated into the PNG

**Comment by codescale** [comment]
Hi. Can you tell me which browser you‘re using?

**Comment by armaccloud** [comment]
Yes, Firefox 89.0.1 (64-bit) on Linux Pop!_OS 20.10.
I have just now tried it in Brave Browser (which is based on Chromium); there the PNG is in good formatting. So it seems to be going wrong in Firefox specifically.

**Comment by codescale** [comment]
I implemented a fix in #12
Do you think you can verify it? Do you know how you could do it? Thx.

**Comment by armaccloud** [comment]
Hi @codescale , I have just tested it out and it works like a charm!
Thank you for picking this up so quickly.
